paths:
  /api/products:
    get:
      summary: Get Products
      description: Obtener productos con paginación y ordenamiento
      parameters:
        - name: limit
          in: query
          description: Limitar el número de productos
          required: false
          schema:
            type: integer
        - name: page
          in: query
          description: Página de resultados
          required: false
          schema:
            type: integer
        - name: sort
          in: query
          description: Ordenar productos (asc/desc)
          required: false
          schema:
            type: string
            enum: [asc, desc]
      responses:
        '200':
          description: Productos obtenidos con éxito
        '400':
          description: Error en los parámetros de consulta
        '500':
          description: Error interno del servidor
    post:
      summary: Post a product
      description: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Producto creado con éxito
        '400':
          description: Error en los datos enviados
        '500':
          description: Error interno del servidor
  /api/products/{pid}:
    put:
      summary: Edit a product
      description: Editar un producto existente
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
            example: 6676217872ea2c2e9458758f
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                thumbnails:
                  type: array
                  items:
                    type: string
                  example: ["https://m.media-amazon.com/images/I/5125bFpYbiL._AC_SL1000_.jpg"]
                category:
                  type: string
                  example: notebooks
      responses:
        '200':
          description: Producto editado con éxito
        '400':
          description: Error en los datos enviados
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor
    delete:
      summary: Delete a product
      description: Eliminar un producto existente
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
            example: 667620b572ea2c2e9458757f
      responses:
        '200':
          description: Producto eliminado con éxito
        '400':
          description: Error en los datos enviados
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor
components:
  responses:
    DataTypeError:
      description: Error en el tipo de dato
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: DATA_TYPE
    InvalidArguments:
      description: Argumentos inválidos
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: INVALID_ARGUMENTS
    AuthenticationError:
      description: Error de autenticación
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string