paths:
  /api/products:

    get:
      summary: Get Products
      description: Get products with pagination and sorting
      parameters:
        - name: limit
          in: query
          description: Limit the number of products
          required: false
          schema:
            type: integer
        - name: page
          in: query
          description: Results page
          required: false
          schema:
            type: integer
        - name: sort
          in: query
          description: Sort products (asc/desc)
          required: false
          schema:
            type: string
            enum: [asc, desc]
      responses:
        '200':
          description: Successfully obtained products
        '400':
          description: Query parameters error
        '500':
          description: Internal Server Error

    post:
      summary: Post a product
      description: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: "Product Title"
                  example: "Example Product"
                description:
                  type: string
                  description: "Description"
                  example: "Description of the product"
                price:
                  type: number
                  description: "price"
                  example: 100
                code:
                  type: string
                  description: "unique code"
                  example: "PROD001"
                stock:
                  type: integer
                  description: "quantity"
                  example: 100
                thumbnail:
                  type: string
                  description: "image URL"
                  example: "https://example.com/imagen.jpg"
      responses:
        '201':
          description: Product Successfully created
        '400':
          description: Data Error
        '500':
          description: Server Error

    put:
      summary: Edit a product
      description: Edit an existing product
      parameters:
        - name: pid
          in: path
          required: true
          description: Product ID
          schema:
            type: string
            example: 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                thumbnails:
                  type: array
                  items:
                    type: string
                  example: imageURL
                category:
                  type: string
                  example: notebooks
      responses:
        '200':
          description: Successfully edited product
        '400':
          description: Data Error
        '404':
          description: Product not found
        '500':
          description: Server Error